### ISSUE TITLE
QBS can't find LiriUtils

### ISSUE THREAD

**Issue by CheeryLee** [lirios/libliri#2]
I'm trying to build libliri, but there is no any success. I get an error:
`/home/alex/liri/libliri/src/core/core.qbs:2:8 import LiriUtils not found`
All Liri's files are in `/home/alex/liri/install_root`. I launch building process with this command:
`qbs -d build qbs.installRoot:/home/alex/liri qbs.installPrefix:/install_root profile:qt5 `
So, there is LiriUtils folder in `/home/alex/liri/install_root/share/qbs/imports/`. 
What am I doing wrong?

**Comment by plfiorini** [comment]
Update liri-qbs-shared-git
